version: '3'

services:
  analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    image: analyzer:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ${CONFIG_PATH}:/app/analyzer/config.yaml
