
data:
  - path: data/data.json
    description: |
      date - column with date
      row_title_column - column with name of well. One well can be included many times in the report.
      column_268 – column with oil production losses per 24-hour shift (tons/day).
      column_281 – column with planned water cut coefficient from geologists (in percent).
      column_310 – column with oil production of the well for 24 hours of operation (tons/day).
      column_314 – a column with planned indicators of daily oil production from geologists (tons/day).
      column_331 – column with the difference between planned oil production and actual oil production (tons/day).
      column_354 – column with data on well fluid production for 24 hours of operation (m³/day).
      column_362 - column with data on the actual water cut of the well (in percent).
      column_364 – column with information about gas production (m³/day).
      column_370 – column with oil density data (tons/m³).
      column_372 – column with information about the actual operation of the well (hours).
      column_386 – column with data on fluid production, taking into account intra-shift losses (m³/day).
      column_475 – column with planned fluid production from geologists (m³/day).

build_plots: false
#bot_api: 6004874058:AAHFjEWq6tBg5mGGGt8pF0h-nE_3JfMOuOU
db_name: "user_data.sql"
bot_api: "6244896218:AAFwtx-NsiIoC24fu5VHahWSB9Du0deMqZg"
#bot_api: "6095869124:AAFhuwDZElDiDPrNXLot7ilYiCNu5np56nA"
bot_name: auto_analyzer
demo: [false, 10, false]